development:
  MAILGUN_SMTP_PORT: '587'
  MAILGUN_SMTP_SERVER: smtp.mailgun.org
  MAILGUN_SMTP_LOGIN: postmaster@app4032012.mailgun.org
  MAILGUN_SMTP_PASSWORD: 2lvtpcyfh9z1
  MAILGUN_DOMAIN: app4032012.mailgun.org
test:
  MAILGUN_SMTP_PORT: '587'
  MAILGUN_SMTP_SERVER: smtp.mailgun.org
  MAILGUN_SMTP_LOGIN: postmaster@app4032012.mailgun.org
  MAILGUN_SMTP_PASSWORD: 2lvtpcyfh9z1
  MAILGUN_DOMAIN: app4032012.mailgun.org
production:
  MAILGUN_SMTP_PORT: '587'
  MAILGUN_SMTP_SERVER: smtp.mailgun.org
  MAILGUN_SMTP_LOGIN: postmaster@app4032012.mailgun.org
  MAILGUN_SMTP_PASSWORD: 2lvtpcyfh9z1
  MAILGUN_DOMAIN: app4032012.mailgun.org

MAILGUN_API_KEY: key-746mtm6knh5tbrqh-jjgnc7ppumialy3
MAILGUN_API_URL: https://api.mailgun.net/v2
MAILGUN_API_FULL_URL: https://api:key-746mtm6knh5tbrqh-jjgnc7ppumialy3@api.mailgun.net/v2/app4032012.mailgun.org/messages