development:
  MAILGUN_SMTP_PORT: '587'
  MAILGUN_SMTP_SERVER: smtp.mailgun.org
  MAILGUN_SMTP_LOGIN: postmaster@app5024011.mailgun.org
  MAILGUN_SMTP_PASSWORD: 62jp2h0bmg31
  MAILGUN_DOMAIN: app5024011.mailgun.org
test:
  MAILGUN_SMTP_PORT: '587'
  MAILGUN_SMTP_SERVER: smtp.mailgun.org
  MAILGUN_SMTP_LOGIN: postmaster@app5024011.mailgun.org
  MAILGUN_SMTP_PASSWORD: 62jp2h0bmg31
  MAILGUN_DOMAIN: app5024011.mailgun.org
production:
  MAILGUN_SMTP_PORT: '587'
  MAILGUN_SMTP_SERVER: smtp.mailgun.org
  MAILGUN_SMTP_LOGIN: postmaster@app5024011.mailgun.org
  MAILGUN_SMTP_PASSWORD: 62jp2h0bmg31
  MAILGUN_DOMAIN: app5024011.mailgun.org

MAILGUN_API_KEY: key-0-zv0demvph1krkk9ctbws9vd17xsyb5
MAILGUN_HOST: app5024011.mailgun.org
MAILGUN_API_URL: https://api.mailgun.net/v2
MAILGUN_API_FULL_URL: https://api:key-0-zv0demvph1krkk9ctbws9vd17xsyb5@api.mailgun.net/v2/app5024011.mailgun.org/messages